"""add_data_templates_table

Revision ID: 351d16ecc6a1
Revises: 6af759a1f9ba
Create Date: 2025-12-11 20:25:48.026068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351d16ecc6a1'
down_revision = '6af759a1f9ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('field_definitions', sa.JSON(), nullable=False),
    sa.Column('example_data', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_templates_created_at'), 'data_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_templates_created_by'), 'data_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_data_templates_id'), 'data_templates', ['id'], unique=False)
    op.create_index(op.f('ix_data_templates_name'), 'data_templates', ['name'], unique=False)
    op.drop_index('idx_documents_parse_status', table_name='documents')
    op.drop_index('idx_documents_upload_time', table_name='documents')
    op.create_index(op.f('ix_documents_parse_status'), 'documents', ['parse_status'], unique=False)
    op.create_index(op.f('ix_documents_upload_time'), 'documents', ['upload_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_upload_time'), table_name='documents')
    op.drop_index(op.f('ix_documents_parse_status'), table_name='documents')
    op.create_index('idx_documents_upload_time', 'documents', ['upload_time'], unique=False)
    op.create_index('idx_documents_parse_status', 'documents', ['parse_status'], unique=False)
    op.drop_index(op.f('ix_data_templates_name'), table_name='data_templates')
    op.drop_index(op.f('ix_data_templates_id'), table_name='data_templates')
    op.drop_index(op.f('ix_data_templates_created_by'), table_name='data_templates')
    op.drop_index(op.f('ix_data_templates_created_at'), table_name='data_templates')
    op.drop_table('data_templates')
    # ### end Alembic commands ###
