"""Initial migration

Revision ID: 73ef425805e3
Revises: 
Create Date: 2025-12-10 17:40:08.319676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ef425805e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('generated_data', sa.Text(), nullable=False),
    sa.Column('data_format', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('model_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_history_id'), 'generation_history', ['id'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('api_base', sa.String(length=500), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_config_name'), 'model_configs', ['config_name'], unique=True)
    op.create_index(op.f('ix_model_configs_id'), 'model_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_configs_id'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_config_name'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_generation_history_id'), table_name='generation_history')
    op.drop_table('generation_history')
    # ### end Alembic commands ###
