"""add_traces_and_spans_tables

Revision ID: 7525b8238d5c
Revises: 73ef425805e3
Create Date: 2025-12-10 20:20:02.001582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7525b8238d5c'
down_revision = '73ef425805e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('span_id', sa.String(length=255), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=False),
    sa.Column('parent_span_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.String(length=50), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_span_trace_time', 'spans', ['trace_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_spans_id'), 'spans', ['id'], unique=False)
    op.create_index(op.f('ix_spans_parent_span_id'), 'spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_spans_span_id'), 'spans', ['span_id'], unique=True)
    op.create_index(op.f('ix_spans_start_time'), 'spans', ['start_time'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.String(length=50), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trace_service_time', 'traces', ['service_name', 'start_time'], unique=False)
    op.create_index(op.f('ix_traces_id'), 'traces', ['id'], unique=False)
    op.create_index(op.f('ix_traces_service_name'), 'traces', ['service_name'], unique=False)
    op.create_index(op.f('ix_traces_start_time'), 'traces', ['start_time'], unique=False)
    op.create_index(op.f('ix_traces_trace_id'), 'traces', ['trace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_trace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_start_time'), table_name='traces')
    op.drop_index(op.f('ix_traces_service_name'), table_name='traces')
    op.drop_index(op.f('ix_traces_id'), table_name='traces')
    op.drop_index('idx_trace_service_time', table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_start_time'), table_name='spans')
    op.drop_index(op.f('ix_spans_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_id'), table_name='spans')
    op.drop_index('idx_span_trace_time', table_name='spans')
    op.drop_table('spans')
    # ### end Alembic commands ###
